version: 2
jobs:
  build:
    working_directory: ~/service
    docker:
      - image: python:2
      - image: mysql:latest
        environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD: yes
        - MYSQL_DATABASE: circle-db

    steps:
      - checkout
      - restore_cache:
          key: venv-{{ checksum "requirements.in" }}
      - run:
          name: install dependencies
          command: |
            echo "Installing Redis ..."
            groupadd -r redis && useradd -r -g redis redis
            curl -O http://download.redis.io/redis-stable.tar.gz
            tar xzvf redis-stable.tar.gz
            cd redis-stable
            make
            make install
            cd ..
            echo "Creating virtualenv ..."
            virtualenv venv
            source venv/bin/activate
            echo "Installing dependencies ..."
            pip install pip-tools
            pip-compile --output-file requirements.txt requirements.in
            pip-sync requirements.txt
      - save_cache:
          key: venv-{{ checksum "requirements.in" }}
          paths:
            - venv
      - run:
          name: run tests
          command: |
            source venv/bin/activate
            # TODO: Use dockerize or similar to wait for DB readiness.
            sleep 5
            redis-server &
            export DJANGO_SETTINGS_MODULE=config.environments.ci
            cd server
            celery -A service worker -l info &
            cd ..
            python server/manage.py migrate
            python server/manage.py test service
      - store_artifacts:
          path: test-reports/
          destination: tr1
